config/routes.rb
Rails.application.routes.draw do

 
  resources :line_items
  resources :carts
 root to: 'items#index' 
 get 'admin', to: 'items#admin' 

 devise_for :users
 resources :items



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
mount_uploader :picture, PictureUploader
has_many :line_items, dependent: :destroy


	
	
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
include CurrentCart

before_action :set_cart, only: [:create]
before_action :set_cart, only: [:new, :edit]


def new
	@cart = Cart.new
end

def create
	@cart = Cart.new(cart_params)
end

def show
end

def edit
end


  private

    def cart_params
      params.require(:cart).permit()
    end

end

app/controllers/concerns/current_cart.rb
module CurrentCart
 extend AcriveSupport::Concern

 def set_cart
	 @cart = Cart.find(session[:cart_id])
	 rescue ActiveRecord::RecordNotFound
		 @cart = Cart.create
		 session[:cart_id] = @cart.id
	 end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


	def create
		#@item = Item.create(item_params)
	end

	def destroy

	end



	def index
	 @items = Item.all.paginate(page: params[:page], per_page: 10)
	end

	def show
		@item = Item.find(params[:id])
	end

	def update
	  @item = Item.find(params[:id])
	  if @item.update(item_params)
	    redirect_to(@item)
	  else
	    render "edit"
	  end
	end

	def item_params
		params.require(:item).permit(:name, :price, :picture)
	end

	def admin
		@item = Item.new
		@item.save
	end

end

app/controllers/line_items_controller.rb
class LineItemsController < InheritedResources::Base
include CurrentCart

	def create
		debugger
		item = Item.find(params[:item_id])
		@line_item = @cart.line_items.build(item: item)
		redirect_to root_url
	end

  private

    def line_item_params
      params.require(:line_item).permit(:item_id, :cart_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def catalog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart</h1>

<h2> Ваша корзина </h2>
<ul>
  <% @cart.line_items.each do |item| %>
  <li> <%= item.product.title %> </li>
  <% end %>
</ul>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/items/_item.html.erb
<%= image_tag item.picture.url if item.picture? %>
<%= item.name %>
<%= 'price:'%>
<%=  number_to_currency(item.price) %>

<%= button_to 'в корзину', line_items_path(item_id: item) %>
<%= will_paginate @items %>
<p>

app/views/items/admin.html.erb
admin
<%= form_for(@item) do |f| %>
<div class="field">
<%= f.text_area :name, placeholder: "Name" %>
<%= f.text_area :price, placeholder: "price" %>
<span class="picture">
<%= f.file_field :picture %>
</span>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/items/index.html.erb
<% if current_user %>
  <h2>Товары</h2>
  <%= render @items %>
  <%= link_to 'logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'login', new_user_session_path %>
<% end %>

app/views/items/show.html.erb
<%= image_tag @item.picture.url if @item.picture? %>
<h1> product name 
<%= @item.name %>
</h>
<p>

<h2> Price
<%= @item.price %>
</h>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.item_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @line_item.item_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>